server:
  port: 9999

#dataSource
spring:
  application:
    name: youzanyun-demo
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    url: jdbc:mysql://193.112.109.78:3306/youzanyun?useUnicode=true&characterEncoding=utf8&useSSL=false
    username: root
    password: login
    driver-class-name: com.mysql.jdbc.Driver # com.mysql.cj.jdbc.Driver
  # redis配置(非集群)
#  redis:
#    host: 127.0.0.1
#    port: 6379
#    pool:
#      max-idle: 666
#      min-idle: 8
#      max-active: 888
#      max-wait: 777
    
endpoints:
  enabled: false
  info: 
    enabled: true
  health:
    enabled: true